Repository julep-ai/steadytext, pull requests merged in 2025-08, with the labels that each got.

#81 chore: bump version to 1.4.5 and update SteadyText dependency to >= 2.6.1 for maintenance release
  CHANGELOG.md
  docs/api/generation.md
  docs/postgresql-extension-structured.md
  docs/structured-generation.md
  docs/unsafe-mode.md
  docs/version_history.md
  pg_steadytext/CHANGELOG.md
  pg_steadytext/CLAUDE.md
  pg_steadytext/Dockerfile
  pg_steadytext/INSTALL.md
  pg_steadytext/META.json
  pg_steadytext/scripts/build-postgres-python313.sh
  pg_steadytext/setup.py
Labels: Review effort 1/5

#86 feat: add -h as alias for --help to all CLI subcommands
  steadytext/cli/commands/cache.py
  steadytext/cli/commands/completion.py
  steadytext/cli/commands/daemon.py
  steadytext/cli/commands/embed.py
  steadytext/cli/commands/generate.py
  steadytext/cli/commands/index.py
  steadytext/cli/commands/models.py
  steadytext/cli/commands/rerank.py
  steadytext/cli/commands/vector.py
  steadytext/cli/main.py
  tests/test_cli.py
Labels: Review effort 2/5

#91 feat: add temperature parameter support for text generation
  CHANGELOG.md
  CLAUDE.md
  README.md
  docs/api/cli.md
  docs/api/generation.md
  steadytext/__init__.py
  steadytext/cli/commands/generate.py
  steadytext/core/generator.py
  steadytext/daemon/client.py
  steadytext/daemon/server.py
  steadytext/utils.py
  tests/test_temperature.py
Labels: Review effort 3/5

#99 feat(pg_steadytext): Switch to date-based versioning (yyyy.mm.dd)
  .claude/.gitignore
  .claude/settings.local.backup.json
  .claude/settings.local.json
  .devcontainer/Dockerfile
  .devcontainer/postCreateCommand.sh
  CHANGELOG.md
  CLAUDE.md
  README.md
  docs/api.md
  docs/api/cli.md
  docs/index.md
  docs/migration-guide.md
  docs/version_history.md
  model_replacement_todos.md
  pg_steadytext/CHANGELOG.md
  pg_steadytext/CLAUDE.md
  pg_steadytext/META.json
  pg_steadytext/Makefile
  pg_steadytext/pg_steadytext.control
  pg_steadytext/setup.py
  pg_steadytext/sql/pg_steadytext--1.4.6--2025.8.15.sql
  pg_steadytext/sql/pg_steadytext--2025.8.15.sql
  pyproject.toml
  steadytext/__init__.py
  steadytext/cli/commands/embed.py
  steadytext/cli/commands/models.py
  steadytext/core/embedder.py
  steadytext/core/generator.py
  steadytext/daemon/client.py
  steadytext/models/cache.py
  steadytext/models/loader.py
  steadytext/utils.py
  tests/test_cli.py
  tests/test_steadytext.py
  tests/test_unsafe_mode.py
  tests/test_unsafe_mode_embeddings.py
  uv.lock
Labels: Review effort 4/5

#92 fix: correct GBNF grammar generation for JSON object properties
  .github/workflows/test.yaml
  CHANGELOG.md
  CLAUDE.md
  README.md
  docs/index.md
  docs/version_history.md
  docs/xllamacpp-migration-assessment.md
  model_replacement_todos.md
  pg_steadytext/CHANGELOG.md
  pg_steadytext/META.json
  pg_steadytext/Makefile
  pg_steadytext/pg_steadytext.control
  pg_steadytext/setup.py
  pg_steadytext/sql/pg_steadytext--1.4.6--2025.8.16.sql
  pg_steadytext/sql/pg_steadytext--2025.8.16.sql
  pyproject.toml
  steadytext/__init__.py
  steadytext/core/embedder.py
  steadytext/core/grammar.py
  steadytext/core/structured.py
  tests/conftest.py
  tests/test_cli.py
  tests/test_custom_seed.py
  tests/test_mini_models.py
  tests/test_steadytext.py
  uv.lock
Labels: Review effort 2/5, Review effort 3/5, Review effort 1/5

#101 fix: add schema qualification to all table references in pg_steadytext SQL files
  pg_steadytext/sql/pg_steadytext--2025.8.16--2025.8.17.sql
  pg_steadytext/sql/pg_steadytext--2025.8.17.sql
Labels: Review effort 2/5

#103 fix: fix pg ext & update version to 2025.8.26
  CLAUDE.md
  pg_steadytext/CHANGELOG.md
  pg_steadytext/CLAUDE.md
  pg_steadytext/META.json
  pg_steadytext/Makefile
  pg_steadytext/README.md
  pg_steadytext/pg_steadytext.control
  pg_steadytext/python/config.py
  pg_steadytext/setup.py
  pg_steadytext/sql/pg_steadytext--2025.8.17--2025.8.26.sql
  pg_steadytext/sql/pg_steadytext--2025.8.26.sql
  pg_steadytext/test/pgtap/03_async.sql
  pg_steadytext/test/pgtap/04_structured.sql
  pg_steadytext/test/pgtap/05_cache_daemon.sql
  pg_steadytext/test/pgtap/06_config.sql
  pg_steadytext/test/pgtap/06_streaming.sql
  pg_steadytext/test/pgtap/07_cache_eviction.sql
  pg_steadytext/test/pgtap/08_reranking.sql
  pg_steadytext/test/pgtap/09_ai_summarization.sql
  pg_steadytext/todos.md
Labels: Review effort 4/5, Possible security concern

#104 feat: Enhance DevContainer workflow and CI/CD documentation
  .devcontainer/CI.md
  .devcontainer/docker-compose.build.yml
  .devcontainer/docker-compose.override.yml.example
  .devcontainer/docker-compose.yml
  .devcontainer/rebuild_extension_simple.sh
  .devcontainer/watch_extension.sh
  .github/workflows/devcontainer-ci.yml
  .github/workflows/devcontainer-simple.yml
  .gitignore
  CLAUDE.md
  pg_steadytext/CLAUDE.md
  pg_steadytext/Dockerfile
  pg_steadytext/docker-entrypoint.sh
  pg_steadytext/run_pgtap_tests.sh
  pg_steadytext/test/pgtap/16_timescaledb_compat.sql
  pg_steadytext/test/pgtap/16_timescaledb_integration.sql
Labels: Possible security concern, Review effort 3/5
